package com.ticket.ticketsample.model;

import java.sql.Date;
import java.time.LocalDateTime;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import jakarta.persistence.*;
import lombok.Data;

@Data
@Entity
@Table(name = "tickets")

public class Ticket {
    // we want id to be autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    // for these, we want to put ourselves
    @Column(name = "Title", nullable = false)
    private String title;

    @Column(name = "Subject")
    private String subject;

    @Column(name = "Status")
    private String status;

    @Column(name = "Created_By")
    private String createdBy;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Date createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
